### ISSUE TITLE
No, just no

### ISSUE THREAD

**Issue by shadowfacts** [ProPercivalalb/MapMakingTools#1]
[No, just no.](https://github.com/ProPercivalalb/MapMakingTools/blob/master/src/main/java/mapmakingtools/thread/PlayerStauteThread.java#L10) Under no circumstances should a `while (true)` loop ever be used. Just no. When a user creates a player statue this causes about a 2 second lag spike whenever the player places a block, opens the chat, or runs a command.

There are probably more places where this is happening that I am not aware of.

Just no. Fix this now. This is unaccceptable and should not have made it anywhere near the released mod.

Just no.

**Comment by percivalalb** [comment]
Oh yer, I must have forgot to remove that when I was messing around with stuff. I will see what i can do for the 1.7.10 version but is definitely gone in the new 1.8 version coming soon.

**Comment by shadowfacts** [comment]
@ProPercivalalb I submitted a pull request (#2)
